### ISSUE TITLE
sudo luarocks install lua-resty-auto-ssl still using dehydrated 0.5.0

### ISSUE THREAD

**Issue by ronaldgetz** [GUI/lua-resty-auto-ssl#192] opened 2019-09-25 04:35 UTC
I just tried to install lua-resty-auto-ssl using luarocks command below:
`sudo luarocks install lua-resty-auto-ssl`

But it is still using dehydrated version 0.5.0 that has a bug of getting the Replay-Nonce header from letsencrypt during validation. I have to update the dehydrated file to make it works!

Can we update the luarocks repo?

**Comment by im-erikjohansson** [comment] 2019-09-25 06:32
According to a [post](https://community.letsencrypt.org/t/trying-to-understand-urnerror-badnonce/102652) on the letsencrypt forums letsencrypt changed their CDN yesterday which is causing problems with the 0.5.0 version of dehydrated.
The planned 0.13.0 release looks to include 0.6.5 of dehydrated which is said to fix this problem.

**Comment by ronaldgetz** [comment] 2019-09-25 06:58
Thank you @im-erikjohansson.

As for anyone who is facing similar issue, you will need to update the 'dehydreated' file located at ' /usr/local/openresty/luajit/bin/resty-auto-ssl/dehydrated'.

Update the following lines:
`REAL_LICENSE="$(http_request head "${CA_TERMS}" | (grep Location: || true) | awk -F ': ' '{print $2}' | tr -d '\n\r')"`
to
`REAL_LICENSE="$(http_request head "${CA_TERMS}" | (grep **-i** Location: || true) | awk -F ': ' '{print $2}' | tr -d '\n\r')"`

AND 

`  # Retrieve nonce from acme-server
  if [[ ${API} -eq 1 ]]; then
    nonce="$(http_request head "${CA}" | grep Replay-Nonce: | awk -F ': ' '{print $2}' | tr -d '\n\r')"
  else
    nonce="$(http_request head "${CA_NEW_NONCE}" | grep Replay-Nonce: | awk -F ': ' '{print $2}' | tr -d '\n\r')"
  fi`

to

`  # Retrieve nonce from acme-server
  if [[ ${API} -eq 1 ]]; then
    nonce="$(http_request head "${CA}" | grep **-i** Replay-Nonce: | awk -F ': ' '{print $2}' | tr -d '\n\r')"
  else
    nonce="$(http_request head "${CA_NEW_NONCE}" | grep **-i** Replay-Nonce: | awk -F ': ' '{print $2}' | tr -d '\n\r')"
  fi`

**Comment by sweet-greg** [comment] 2019-09-25 09:15
@ronaldgetz thank you for that, perfect temporary fix. 
Any idea when the 0.13.0 release is scheduled?

**Comment by dvigueras** [comment] 2019-09-25 09:41
The 0.13.0 release needs to be released as soon as possible. Anything that I could do to help with this?

**Comment by sweet-greg** [comment] 2019-09-26 09:11
@GUI can you chime in on this? This seems to be caused by HTTP/2 case sensitive headers.
Dehydrated fixed [that](https://github.com/lukas2511/dehydrated/commit/e4e712c03ad70bd5100af1333c2801f4b5baa89a#diff-f8a3fd80bfeb8e8456d63862cb71da83)

**Comment by andreasschroth** [comment] 2019-09-27 08:40
This should be high-priority. I don't want to be demanding or anything as I know how much work it is to maintain Open Source projects, but please release a new version of this one, as no new SSL certs can be issued anymore.

**Comment by ezbik** [comment] 2019-09-29 09:01
Cool, also it fixed this on my side

```
Details:
{
  "type": "urn:acme:error:badNonce",
  "detail": "JWS has no anti-replay nonce",
  "status": 400
}
```

**Comment by GUI** [comment] 2019-09-30 05:28
Sorry for the headaches caused by the delay on this everyone! v0.13.0 is now released which includes the newer version of dehydrated bundled in. Give a shout if you're still seeing any issues with the new release.

And thanks to everyone for reporting this and the temporary workarounds!

**Closed by GUI** 2019-09-30 05:28 UTC

**Comment by felixbuenemann** [comment] 2019-10-23 14:20
Here are @ronaldgetz changes as a patch for easier hotfixing:

```diff
--- luajit/bin/resty-auto-ssl/dehydrated	2019-10-23 16:05:48.322378013 +0200
+++ luajit/bin/resty-auto-ssl/dehydrated	2019-10-23 16:08:12.359383225 +0200
@@ -296,7 +296,7 @@
   else
     # Check if private account key exists, if it doesn't exist yet generate a new one (rsa key)
     if [[ ! -e "${ACCOUNT_KEY}" ]]; then
-      REAL_LICENSE="$(http_request head "${CA_TERMS}" | (grep Location: || true) | awk -F ': ' '{print $2}' | tr -d '\n\r')"
+      REAL_LICENSE="$(http_request head "${CA_TERMS}" | (grep -i Location: || true) | awk -F ': ' '{print $2}' | tr -d '\n\r')"
       if [[ -z "${REAL_LICENSE}" ]]; then
         printf '\n' >&2
         printf 'Error retrieving terms of service from certificate authority.\n' >&2
@@ -523,9 +523,9 @@

   # Retrieve nonce from acme-server
   if [[ ${API} -eq 1 ]]; then
-    nonce="$(http_request head "${CA}" | grep Replay-Nonce: | awk -F ': ' '{print $2}' | tr -d '\n\r')"
+    nonce="$(http_request head "${CA}" | grep -i Replay-Nonce: | awk -F ': ' '{print $2}' | tr -d '\n\r')"
   else
-    nonce="$(http_request head "${CA_NEW_NONCE}" | grep Replay-Nonce: | awk -F ': ' '{print $2}' | tr -d '\n\r')"
+    nonce="$(http_request head "${CA_NEW_NONCE}" | grep -i Replay-Nonce: | awk -F ': ' '{print $2}' | tr -d '\n\r')"
   fi

   # Build header with just our public key and algorithm information
```
